name: connect to the database

on:
  push:
    branches:
      - main

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo "Workflow is running"